repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-byte-order-marker
        stages: ['commit']
      - id: check-case-conflict
        stages: ['commit']
      - id: check-executables-have-shebangs
        stages: ['commit']
      - id: check-json
        stages: ['commit']
      - id: check-xml
        stages: ['commit']
      - id: check-yaml
        stages: ['commit']
      - id: check-merge-conflict
        stages: ['commit']
      - id: detect-private-key
        stages: ['commit']
      - id: end-of-file-fixer
        stages: ['commit']
      - id: flake8
        stages: ['commit']
      - id: trailing-whitespace
        stages: ['commit']

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.7.3
    hooks:
      - id: terraform_fmt
        stages: ['commit']
      - id: terraform_validate_no_variables
        stages: ['commit']
      - id: terraform_docs
        stages: ['commit']

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.15.0
    hooks:
      - id: yamllint
        stages: ['commit']

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs.git
    rev: v1.1.0
    hooks:
      - id: markdown-toc
        stages: ['commit']
